version: "2.2"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  internal-api:
    build:
      context: .
      dockerfile: LocalDockerfile
    volumes:
      - .:/opt/internal-api
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - INTERNAL_API_DEBUG=True
      - FLASK_ENVIRONMENT_TYPE=development
      - PYTHONASYNCIODEBUG=1
      - PYTHONUNBUFFERED=1
    links:
      - redis
    privileged: true
    depends_on:
      - redis
    ports:
      - "8763:8763"
